### ISSUE TITLE
Maak een nieuwe pagina aan voor het project zelf

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/Portfolio#14]
**Parent issue**
https://app.gitkraken.com/glo/board/XcPP3FuFhQAPHXwM/card/XfevmyNdWgAQmCIa

**Description**
Wanneer op de afbeelding geklikt wordt bij het tabblad project, dan moet je op de nieuwe pagina komen.
Met uitleg over; 
- waarom dit project gemaakt is,
- van het project zelf.

Parent issue: https://app.gitkraken.com/glo/board/XcPP3FuFhQAPHXwM/card/XfIWf_cC6AAPsvRo

**TODO**
- [x] Maak de link naar de nieuwe pagina
- [x] Creeër het tekst vlak zoals je wilt
- [x] Creeër de foto vlakken die je kan
- [x] Documenteer
- [x] Test
