### ISSUE TITLE
WebScraping project should be viewable

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/Portfolio#16]
**Description**
Similar to Hangman, a new page should be created to display the WebScraping project as well. The layout should be the same as Hangman. 

**TODO**
- [x] Create pictures of the project
- [x] Create a new page with the same look as Hangman
- [x] Create context for the text fields
- [x] Test 
- [x] Document
