### ISSUE TITLE
Zorg dat alles goed werk zoals het zou moeten

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/Portfolio#29]
**Description**
Je moet alle pagina's langs gaan en kijken of alles goed werkt. Dus op alle links klikken en bekijken of het goed gaat zoals het zou moeten. Tekst controleren op eventuele typ fouten etc.

*! Verander de tekst van ander half jaar ervaring naar 2 jaar, aangezien je ondertussen inderdaad al 2 jaar ervaring hebt*

**TODO**
- [x] Controle of alle afbeeldingen goed geladen worden
- [x] Controle of alle links werken (projecten, algemene footer, menu items etc)
- [x] Controle op eventuele typfouten
- [x] Controle op de resizing op de verschillende devices
