### ISSUE TITLE
Portfolio project zelf ook toevoegen aan de projecten!!

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/Portfolio#30]
**Description**
Zorg dat je meer informatie over je eigen portfolio website ook gaat geven. Aangezien dit ook best belangrijk is natuurlijk

**TODO**
- [x] zelfde opzet als Hangman etc.
- [x] Verwijs naar Github
~~- [ ] Verwijs naar Wiki van het project~~
- [x] afbeeldingen zijn niet nodig lijkt me.. (is de website zelf)

**Comment by EvilAngel94** [comment]
Verwijzen naar de Wiki heeft niet echt nut, aangezien alles al gewoon in de applciatie staat. En een uitgebreidere uitleg staat in het portfolio tab blad zelf. 
De documentatie van het project is eigenlijk puur de teksten die gebruikt zijn, en weinig over de technologie dus er zit geen meerwaarde in om een wiki te maken.
