### ISSUE TITLE
Maak een afbeelding voor het portfolio project

### ISSUE THREAD

**Issue by EvilAngel94** [EvilAngel94/Portfolio#31]
**Description**
Maak een nieuwe afbeelding voor het portfolio project. Het principe moet het zoals de afbeelding zijn.

**TODO**
- [x] maak nieuwe afbeelding
- [x] sla de afbeelding op
- [x] gebruik de afbeelding in portfolio

**Afbeelding**
**Voorbeeld**
![image](https://app.gitkraken.com/api/glo/boards/5e382c310e8c72001100fa1f/attachments/5e4122faa326a20010886a72)

**Nieuwe afbeelding**
![image](https://app.gitkraken.com/api/glo/boards/5e382c310e8c72001100fa1f/attachments/5e412fbc184ba700102f057f)
